### PR TITLE
Add Spanish (es-rES) language

### PR DESCRIPTION
**Pull request by oscfdezdz**

### CODE REVIEW

**Review by oscfdezdz — COMMENTED** [review]
The word "actividadlo" should be separated as they were before ("actividad lo"), as they are two different words.

**Comment by AdrianMiozga** [comment]
Oh, I don’t know how that happened – I didn’t mean to do it. Does everything look alright now?

**Comment by oscfdezdz** [comment]
Yes, all looking fine!

**Comment by AdrianMiozga** [comment]
Okay, then. Thank you for your contribution, and sorry for the formatting mistake in the beginning!

**Pull request merged**
